
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
virtualenv:
  system_site_packages: true
# command to install dependencies
install:
  - pip install .
before_install:  # http://stackoverflow.com/questions/40359049/no-module-named-scipy-while-it-is-installed
  - pip install scipy
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
# command to run tests
script:
- py.test -v tests/
